Repository v6d-io/v6d, pull requests merged in 2023-01, with the labels that each got.

#1131 Add a command to build a kind cluster with a local registry for reducing the time to load docker-image
  k8s/Makefile
  k8s/test/hack/build-kind-cluster-with-local-registry.sh
Labels: codeball:needs-review

#1138 Implements accmulate support for vineyard.io.open()
  k8s/test/e2e/assembly-demo/assembly-distributed.py
  k8s/test/e2e/assembly-demo/assembly-job2.py
  k8s/test/e2e/assembly-demo/distributed-job2.py
  k8s/test/e2e/assembly-demo/distributed-job3.py
  k8s/test/e2e/failover-demo/build-distributed-object-step2.py
  k8s/test/e2e/failover-demo/get-distributed-object.py
  k8s/test/e2e/failover-demo/get-local-object.py
  k8s/test/e2e/repartition-demo/dask-repartition.py
  k8s/test/e2e/repartition-demo/job2.py
  k8s/test/e2e/workflow-demo/job2.py
  modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
  modules/io/python/drivers/io/adaptors/read_orc.py
  modules/io/python/drivers/io/adaptors/read_parquet.py
  modules/io/python/drivers/io/adaptors/read_vineyard_dataframe.py
  modules/io/python/drivers/io/stream.py
  modules/io/python/drivers/io/tests/test_open.py
  python/vineyard/cli.py
  python/vineyard/data/dataframe.py
  python/vineyard/io/stream.py
  python/vineyard/launcher/script.py
Labels: codeball:needs-review

#1140 Make sure chunks are persisted in IO readers
  modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
  modules/io/python/drivers/io/adaptors/read_orc.py
  modules/io/python/drivers/io/adaptors/read_parquet.py
  python/vineyard/core/builder.py
Labels: codeball:needs-review

#1141 Add container name as a option to kube_ssh.sh
  modules/io/python/drivers/io/kube_ssh.sh
Labels: codeball:needs-review

#1142 Deploy preview site to netlify
  .github/workflows/cancel.yaml
  .github/workflows/codeball.yml
  .github/workflows/docs.yaml
Labels: codeball:approved

#1144 Allow pushing in docs CI
  .github/workflows/docs.yaml
Labels: codeball:needs-review

#1149 Make sure use dataframe in GlobalDataFrame
  modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
  modules/io/python/drivers/io/adaptors/read_orc.py
  modules/io/python/drivers/io/adaptors/read_parquet.py
Labels: codeball:approved

#1145 Add all globalobjects and localobjects created by one job to the relevant configmap
  k8s/pkg/schedulers/common.go
Labels: codeball:needs-review

#1154 Less copy between in-process memory and vineyard during building a fragment
  modules/basic/ds/arrow.cc
  modules/basic/ds/arrow.h
  modules/basic/ds/arrow_utils.h
  modules/graph/fragment/arrow_fragment.h
  modules/graph/fragment/arrow_fragment.vineyard-mod
  modules/graph/fragment/arrow_fragment_builder_impl.h
  modules/graph/fragment/arrow_fragment_impl.h
  modules/graph/fragment/property_graph_utils.h
  modules/graph/fragment/property_graph_utils_impl.h
  modules/graph/fragment/property_graph_utils_uint32.cc
  modules/graph/fragment/property_graph_utils_uint64.cc
  modules/graph/loader/arrow_fragment_loader.cc
  modules/graph/loader/arrow_fragment_loader_impl.h
  src/client/client.cc
  src/client/ds/object_meta.cc
  src/client/ds/object_meta.h
  src/common/util/env.cc
Labels: codeball:needs-review

#1156 Use -1 to indicates unknown chunk index inside a global dataframes
  .github/workflows/build-vineyardd-and-wheels-linux.yaml
  docker/pypa/Dockerfile.manylinux1
  docker/pypa/Dockerfile.manylinux1-wheel
  modules/basic/ds/dataframe.vineyard-mod
  python/vineyard/contrib/ml/mxnet.py
  python/vineyard/contrib/ml/pytorch.py
  python/vineyard/contrib/ml/tensorflow.py
  python/vineyard/data/dataframe.py
Labels: codeball:needs-review

#1137 Revise all e2e tests to use the kind cluster with local registry
  .github/workflows/vineyard-operator.yaml
  k8s/Makefile
  k8s/README.md
  k8s/cmd/main.go
  k8s/config/manager/kustomization.yaml
  k8s/test/e2e/Makefile
  k8s/test/e2e/assembly-demo/assembly-job.yaml
  k8s/test/e2e/assembly-demo/assembly-job1.py
  k8s/test/e2e/assembly-demo/assembly-job2.py
  k8s/test/e2e/assembly-demo/distributed-job1.py
  k8s/test/e2e/assembly-demo/distributed-job2.py
  k8s/test/e2e/assembly-demo/distributed-job3.py
  k8s/test/e2e/assembly/distributed-assembly-e2e.yaml
  k8s/test/e2e/assembly/local-assembly-e2e.yaml
  k8s/test/e2e/autogenerated-helm-chart/e2e.yaml
  k8s/test/e2e/failover-demo/backup.py
  k8s/test/e2e/failover-demo/failover-job.yaml
  k8s/test/e2e/failover-demo/get-object.yaml
  k8s/test/e2e/failover-demo/recover.py
  k8s/test/e2e/failover/e2e.yaml
  k8s/test/e2e/kind-with-local-registry.yaml
  k8s/test/e2e/repartition-demo/job1.py
  k8s/test/e2e/repartition-demo/job2.py
  k8s/test/e2e/repartition-demo/repartition-dask-helm-values.yaml
  k8s/test/e2e/repartition-demo/repartition-job.yaml
  k8s/test/e2e/repartition/dask-repartition-e2e.yaml
  k8s/test/e2e/scheduling-outside-cluster/e2e.yaml
  k8s/test/e2e/serialize-demo/serialize-demo.yaml
  k8s/test/e2e/serialize/e2e.yaml
  k8s/test/e2e/sidecar-demo/sidecar-with-custom-sidecar.yaml
  k8s/test/e2e/sidecar-demo/sidecar-with-default-sidecar.yaml
  k8s/test/e2e/sidecar/e2e.yaml
  k8s/test/e2e/spill/e2e.yaml
  k8s/test/e2e/workflow-demo/workflow-job1.yaml
  k8s/test/e2e/workflow-demo/workflow-job2.yaml
  k8s/test/e2e/workflow/e2e.yaml
  k8s/test/hack/build-kind-cluster-with-local-registry.sh
  k8s/test/hack/delete-kind-cluster-with-local-registry.sh
Labels: codeball:needs-careful-review

#1153 Add the missing code block in the vineyard operator doc
  docs/notes/how-to-use-vineyard-operator.rst
Labels: codeball:approved

#1157 Add commands for remote installation of vineyard operator
  k8s/README.md
Labels: codeball:approved

#1128 Add vineyard operator architecture
  docs/images/vineyard_operator_arch.png
  docs/notes/vineyard-operator.rst
Labels: codeball:needs-review

#1158 Drop the intermediate stream when ensure it has finished
  .github/workflows/build-compatibility.yml
  .github/workflows/build-vineyardd-and-wheels-macos.yaml
  modules/io/python/drivers/io/adaptors/dump_dataframe.py
  modules/io/python/drivers/io/adaptors/parse_bytes_to_dataframe.py
  modules/io/python/drivers/io/adaptors/parse_dataframe_to_bytes.py
  modules/io/python/drivers/io/stream.py
  python/client.cc
  python/vineyard/io/stream.py
  setup.cfg
  setup.cfg.in
  src/client/client_base.cc
  src/client/client_base.h
  src/common/util/protocols.cc
  src/common/util/protocols.h
  src/server/async/socket_server.cc
  src/server/async/socket_server.h
  src/server/memory/stream_store.cc
Labels: codeball:needs-review

#1164 <version> is part of c++20
  .github/workflows/build-test.yml
  thirdparty/wyhash/wyhash.hpp
Labels: codeball:needs-review

#1165 Support configuring the operatiom image in the vineyardd CR and update relevant doc
  charts/vineyard-operator/templates/vineyardd-crd.yaml
  docs/notes/vineyard-operator.rst
  k8s/apis/k8s/v1alpha1/vineyardd_types.go
  k8s/config/crd/bases/k8s.v6d.io_vineyardds.yaml
  k8s/config/manager/kustomization.yaml
  k8s/controllers/k8s/operation_controller.go
  k8s/pkg/operation/assembly.go
  k8s/pkg/operation/repartition.go
  k8s/pkg/templates/operation/dask-repartition.yaml
  k8s/pkg/templates/operation/distributed-assembly-job.yaml
  k8s/pkg/templates/operation/local-assembly-job.yaml
  k8s/test/e2e/Makefile
  k8s/test/e2e/assembly/distributed-assembly-e2e.yaml
  k8s/test/e2e/vineyardd.yaml
Labels: codeball:needs-review

#1167 Kubernetes CI: build latest vineyardd image from source
  .github/workflows/vineyard-operator.yaml
  k8s/Makefile
  k8s/test/e2e/vineyardd.yaml
Labels: codeball:needs-review
