Repository v6d-io/v6d, pull requests merged in 2023-02, with the labels that each got.

#1173 Replace the etcd image with vineyardd image
  k8s/controllers/k8s/sidecar_controller.go
  k8s/controllers/k8s/vineyardd_controller.go
  k8s/pkg/templates/etcd/etcd.yaml
Labels: codeball:approved

#1189 Update the comments after preview the generated docs to netlify
  .github/workflows/docs.yaml
Labels: codeball:approved

#1188 Fixes some compilation errors under latest clang
  modules/graph/CMakeLists.txt
  modules/graph/loader/basic_ev_fragment_loader_impl.h
  modules/graph/loader/fragment_loader_utils.cc
  python/core.cc
  python/vineyard/core/codegen/cpp.py
  src/client/client_base.cc
  src/client/ds/object_meta.cc
  src/client/ds/object_meta.h
Labels: codeball:needs-review

#1195 Enable error check in seal() to prevent uncaught exceptions and crashes.
  modules/basic/stream/byte_stream.h
  modules/basic/stream/dataframe_stream.cc
  modules/basic/stream/dataframe_stream.h
  modules/basic/stream/recordbatch_stream.cc
  modules/basic/stream/recordbatch_stream.h
  modules/graph/fragment/arrow_fragment_builder_impl.h
  modules/graph/fragment/arrow_fragment_group.cc
  modules/graph/fragment/arrow_fragment_group.h
  modules/graph/fragment/arrow_fragment_impl.h
  modules/graph/fragment/gar_fragment_builder_impl.h
  modules/graph/loader/basic_ev_fragment_loader.h
  modules/graph/loader/basic_ev_fragment_loader_impl.h
  modules/graph/loader/fragment_loader_utils.cc
  modules/graph/loader/gar_fragment_loader.h
  modules/graph/loader/gar_fragment_loader_impl.h
  modules/graph/vertex_map/arrow_local_vertex_map.h
  modules/graph/vertex_map/arrow_local_vertex_map_impl.h
  modules/graph/vertex_map/arrow_vertex_map.h
  modules/graph/vertex_map/arrow_vertex_map_impl.h
  modules/hosseinmoein-dataframe/hosseinmoein_dataframe.h
  python/core.cc
  python/vineyard/core/codegen/cpp.py
  src/client/ds/blob.cc
  src/client/ds/blob.h
  src/client/ds/i_object.cc
  src/client/ds/i_object.h
  src/client/ds/stream.h
  src/common/util/protocols.cc
  test/custom_vector_test.cc
  test/runner.py
  test/stream_test.cc
Labels: codeball:needs-review

#1197 Refine collection API and tensor/dataframe APIs
  modules/basic/ds/dataframe.cc
  modules/basic/ds/dataframe.h
  modules/basic/ds/tensor.cc
  modules/basic/ds/tensor.h
  modules/graph/loader/arrow_fragment_loader.cc
  src/client/client.cc
  src/client/ds/collection.h
  src/server/memory/usage.h
  test/global_object_test.cc
  test/runner.py
Labels: codeball:needs-review

#1198 Implements `vineyard::Table` using the Collection API for simplication
  CMakeLists.txt
  modules/basic/ds/arrow.cc
  modules/basic/ds/arrow.h
  modules/basic/ds/arrow.vineyard-mod
  modules/basic/ds/arrow_utils.cc
  modules/basic/ds/arrow_utils.h
  modules/basic/ds/dataframe.cc
  modules/basic/ds/dataframe.h
  modules/basic/ds/tensor.cc
  modules/basic/ds/tensor.h
  python/vineyard/core/codegen/cpp.py
  src/client/ds/collection.h
  src/client/ds/i_object.h
  test/arrow_data_structure_test.cc
  test/release_test.cc
Labels: codeball:needs-review

#1199 Bump up golang.org/x/net from 0.2.0 to 0.7.0
  k8s/go.mod
  k8s/go.sum
Labels: codeball:approved

#1200 Fix kubernetes ci errors
  k8s/go.mod
  k8s/go.sum
Labels: codeball:approved

#1201 Add labels support and APIs on client
  python/client.cc
  python/core.cc
  src/client/client_base.cc
  src/client/client_base.h
  src/client/ds/object_meta.cc
  src/client/ds/object_meta.h
  src/common/util/protocols.cc
  src/common/util/protocols.h
  src/server/async/socket_server.cc
  src/server/async/socket_server.h
  src/server/server/vineyard_server.cc
  src/server/server/vineyard_server.h
  test/object_meta_test.cc
Labels: codeball:needs-careful-review

#1209 Fix k8s module dependency conflicts
  k8s/Makefile
  k8s/apis/k8s/v1alpha1/zz_generated.deepcopy.go
  k8s/cmd/commands/create/create.go
  k8s/cmd/commands/create/create_backup.go
  k8s/cmd/commands/deploy/deploy_certmanager.go
  k8s/cmd/commands/dryschedule/dryschedule_workload.go
  k8s/cmd/commands/flags/managers_flags.go
  k8s/cmd/commands/root.go
  k8s/go.mod
  k8s/go.sum
  k8s/pkg/schedulers/scheduling.go
  k8s/pkg/schedulers/schedulingstate.go
  k8s/test/e2e/Makefile
  k8s/test/e2e/assembly-demo/assembly-job.yaml
Labels: codeball:needs-review

#1210 Update the dry{apply/delete} and delete some duplication code
  k8s/cmd/commands/create/create_backup.go
  k8s/cmd/commands/create/create_recover.go
  k8s/cmd/commands/delete/delete.go
  k8s/cmd/commands/delete/delete_backup.go
  k8s/cmd/commands/delete/delete_certmanager.go
  k8s/cmd/commands/delete/delete_operator.go
  k8s/cmd/commands/delete/delete_recover.go
  k8s/cmd/commands/delete/delete_vineyard_cluster.go
  k8s/cmd/commands/delete/delete_vineyard_deployment.go
  k8s/cmd/commands/delete/delete_vineyardd.go
  k8s/cmd/commands/deploy/deploy.go
  k8s/cmd/commands/deploy/deploy_certmanager.go
  k8s/cmd/commands/deploy/deploy_operator.go
  k8s/cmd/commands/deploy/deploy_vineyard_cluster.go
  k8s/cmd/commands/deploy/deploy_vineyard_deployment.go
  k8s/cmd/commands/deploy/deploy_vineyardd.go
  k8s/cmd/commands/dryapply/dryapply.go
  k8s/cmd/commands/drydelete/drydelete.go
  k8s/cmd/commands/flags/backup_flags.go
  k8s/cmd/commands/flags/global_flags.go
  k8s/cmd/commands/flags/managers_flags.go
  k8s/cmd/commands/flags/vineyardd_flags.go
  k8s/cmd/commands/root.go
  k8s/cmd/commands/schedule/schedule.go
  k8s/cmd/commands/schedule/schedule_workload.go
  k8s/cmd/commands/start/start.go
  k8s/cmd/commands/start/start_manager.go
  k8s/cmd/commands/util/client.go
  k8s/cmd/commands/util/parse.go
  k8s/cmd/commands/util/validate.go
Labels: codeball:needs-review
