Repository v6d-io/v6d, pull requests merged in 2024-07, with the labels that each got.

#1760 Adapt k8s to v1.19.3.
  docs/notes/cloud-native/deploy-kubernetes.rst
  docs/notes/cloud-native/vineyard-operator.rst
  docs/notes/developers/faq.rst
  docs/tutorials/data-processing/accelerate-data-sharing-in-kedro.rst
  docs/tutorials/kubernetes/data-sharing-with-vineyard-on-kubernetes.rst
  docs/tutorials/kubernetes/efficient-data-sharing-in-kubeflow-with-vineyard-csi-driver.rst
  go/vineyard/go.mod
  go/vineyard/go.sum
  go/vineyard/pkg/client/client_base.go
  go/vineyard/pkg/common/log/deleg.go
  go/vineyard/pkg/common/log/log.go
  go/vineyard/pkg/common/log/zap/zap.go
  go/vineyard/pkg/common/memory/fd.go
  k8s/cmd/commands/manager/manager.go
  k8s/cmd/commands/util/operator.go
  k8s/config/crd/bases/k8s.v6d.io_backups.yaml
  k8s/config/crd/bases/k8s.v6d.io_sidecars.yaml
  k8s/config/crd/bases/k8s.v6d.io_vineyardds.yaml
  k8s/config/scheduler/config.yaml
  k8s/go.mod
  k8s/go.sum
  k8s/pkg/log/log.go
  k8s/pkg/schedulers/scheduling.go
  k8s/pkg/webhook/sidecar/sidecar_webhook.go
  k8s/test/e2e/Makefile
  k8s/test/e2e/assembly/local-assembly-e2e.yaml
  k8s/test/e2e/autogenerated-helm-chart/e2e.yaml
  k8s/test/e2e/kind-with-local-registry.yaml
  k8s/test/e2e/kind.yaml
  k8s/test/e2e/repartition-demo/job1.py
  k8s/test/e2e/repartition/dask-repartition-e2e.yaml
  k8s/test/hack/build-kind-cluster-with-local-registry.sh
  k8s/test/hack/prepare-e2e.sh
Labels: stale

#1958 Remove libfabric.a from VINEYARD_INSTALL_LIBS
  CMakeLists.txt
Labels: RDMA

#1956 Added GetRemoteBlob interface to support user-specified buffer for data storage.
  src/client/rpc_client.cc
  src/client/rpc_client.h
  src/common/rdma/rdma_client.h
  test/rdma_blob_perf_test.cc
Labels: RDMA

#1959 Prevents objects from being deleted during transfer.
  src/client/rpc_client.cc
  src/client/rpc_client.h
  src/common/util/protocols.cc
  src/common/util/protocols.h
  src/server/async/socket_server.cc
  src/server/async/socket_server.h
  src/server/server/vineyard_server.cc
  src/server/server/vineyard_server.h
Labels: bug, component:vineyardd

#1968 Fix memory leak when client crashed
  src/common/rdma/rdma.h
  src/common/rdma/rdma_server.cc
Labels: bug, RDMA
